/**
 * Careers / Recruitment shared type definitions.
 *
 * Used by:
 * - Public career pages
 * - Job detail pages
 * - CMS / API layer
 * - Admin career pages
 * - Job applications
 * - Recruitment pipeline
 */

import type { ObjectId } from 'mongodb';

/* -------------------------------------------------------------------------- */
/* Job Types                                                                  */
/* -------------------------------------------------------------------------- */

export type EmploymentType =
  | 'Full-time'
  | 'Part-time'
  | 'Contract'
  | 'Freelance'
  | 'Internship';

export type ExperienceLevel =
  | 'Entry Level'
  | 'Junior'
  | 'Mid Level'
  | 'Senior'
  | 'Lead'
  | 'Manager'
  | 'Internship';

export type RemoteStatus = 'remote' | 'hybrid' | 'on-site';

/**
 * Career job / job posting.
 *
 * The same shape is shared between the CMS, API and public job detail page.
 */
export interface CareerJob {
  _id?: ObjectId | string;

  /* Basic job information */
  title: string;
  slug: string;
  department: string;

  employmentType: EmploymentType | string;
  experienceLevel: ExperienceLevel | string;

  /**
   * Human-readable location.
   *
   * Examples:
   * - "Remote — Worldwide"
   * - "Lahore, Pakistan (Hybrid)"
   */
  location: string;

  /**
   * Optional structured location fields used by JobPosting / GEO data.
   */
  city?: string;
  country?: string;
  remoteStatus: RemoteStatus | string;

  /* Job content */
  shortDescription: string;

  /** Rich HTML generated by the CMS rich-text editor. */
  description: string;

  /** Rich HTML for the responsibilities section. */
  responsibilities: string;

  /** Rich HTML for the requirements section. */
  requirements: string;

  /** Optional rich HTML for nice-to-have qualifications. */
  niceToHave?: string;

  /** Optional rich HTML for benefits and compensation. */
  benefits?: string;

  /** Search/filter/JobPosting skills. */
  skills: string[];

  /**
   * Optional human-readable salary.
   *
   * Example:
   * "$60k – $80k / year"
   */
  salary?: string;

  /** Optional job featured image URL. */
  featuredImage?: string;

  /* Publishing / visibility */
  featured: boolean;
  status: 'open' | 'closed';
  published: boolean;
  archived: boolean;

  /**
   * Dates may be Mongo Date objects internally or ISO/string values after
   * server-side serialization.
   */
  publishedAt?: Date | string;
  closingDate?: Date | string;

  /**
   * Random token used for secure draft previews via ?preview=.
   */
  previewKey?: string;

  /* SEO */
  seoTitle?: string;
  seoDescription?: string;

  /* Audit timestamps */
  createdAt: Date | string;
  updatedAt: Date | string;
}

/* -------------------------------------------------------------------------- */
/* Resume                                                                     */
/* -------------------------------------------------------------------------- */

export interface ResumeFile {
  /**
   * Private/non-public ImageKit file reference.
   */
  imagekitFileId: string;

  fileName: string;
  fileType: string;
  fileSize: number;

  /** Optional normalized file format, e.g. "pdf". */
  format?: string;
}

/* -------------------------------------------------------------------------- */
/* Application Pipeline                                                      */
/* -------------------------------------------------------------------------- */

export interface ApplicationNote {
  text: string;
  author: string;
  createdAt: Date | string;
}

export interface StageHistoryEntry {
  from: string;
  to: string;
  changedBy: string;
  note?: string;
  at: Date | string;
}

/**
 * Pipeline stages.
 *
 * Order matters because stageRank() uses this order.
 */
export const APPLICATION_STAGES = [
  'New',
  'Screening',
  'Shortlisted',
  'Interview',
  'Technical / Role Interview',
  'Final Interview',
  'Offer',
  'Hired',
  'Rejected',
] as const;

export type ApplicationStage = (typeof APPLICATION_STAGES)[number];

/* -------------------------------------------------------------------------- */
/* Job Application                                                            */
/* -------------------------------------------------------------------------- */

export interface JobApplication {
  _id?: ObjectId | string;

  /** Public reference, e.g. SH-APP-1A2B3C4D. */
  referenceId: string;

  /** Related job identifiers. */
  jobId?: ObjectId | string;
  jobSlug?: string;
  jobTitle?: string;

  /**
   * True for general / talent-pool applications that are not tied
   * to a specific job.
   */
  general: boolean;

  /* Candidate identity */
  candidateId?: ObjectId | string;

  firstName: string;
  lastName: string;
  email: string;

  /* Candidate contact/profile */
  phone?: string;
  location?: string;
  currentRole?: string;
  yearsOfExperience?: string;

  /* Professional profiles */
  linkedinUrl?: string;
  githubUrl?: string;
  portfolioUrl?: string;

  /* Hiring information */
  expectedSalary?: string;
  availability?: string;

  /* Application content */
  coverLetter: string;
  additionalInfo?: string;

  /* Resume */
  resume?: ResumeFile | null;

  /* Consent */
  consent: boolean;

  /* Recruitment pipeline */
  stage: ApplicationStage;

  assignedTo?: string;

  internalNotes: ApplicationNote[];
  stageHistory: StageHistoryEntry[];

  /** Optional attribution/source information. */
  source?: string;

  /* Audit timestamps */
  createdAt: Date | string;
  updatedAt: Date | string;
}

/* -------------------------------------------------------------------------- */
/* Candidate                                                                  */
/* -------------------------------------------------------------------------- */

export interface Candidate {
  _id?: ObjectId | string;

  email: string;
  name: string;

  phone?: string;
  location?: string;
  currentRole?: string;

  linkedinUrl?: string;
  githubUrl?: string;
  portfolioUrl?: string;

  resume?: ResumeFile | null;

  summary: string;

  firstAppliedAt: Date | string;
  lastAppliedAt: Date | string;

  createdAt: Date | string;
  updatedAt: Date | string;
}

/* -------------------------------------------------------------------------- */
/* Interviews                                                                 */
/* -------------------------------------------------------------------------- */

export type InterviewStatus =
  | 'Scheduled'
  | 'Confirmed'
  | 'Completed'
  | 'Cancelled'
  | 'Rescheduled'
  | 'No-show';

export interface Interview {
  _id?: ObjectId | string;

  jobId?: ObjectId | string;
  jobTitle?: string;

  candidateId?: ObjectId | string;
  candidateName: string;
  candidateEmail: string;

  type: string;

  date: string;
  time: string;
  timezone?: string;

  interviewer?: string;
  interviewerEmail?: string;

  meetingLink?: string;

  status: InterviewStatus;

  notes?: string;

  createdAt: Date | string;
  updatedAt: Date | string;
}

/* -------------------------------------------------------------------------- */
/* Careers Page Content                                                       */
/* -------------------------------------------------------------------------- */

export interface CareerFaq {
  question: string;
  answer: string;
}

export interface CareerBenefit {
  icon: string;
  title: string;
  description: string;
}

export interface CareerTestimonial {
  name: string;
  position: string;
  department?: string;
  photo?: string;
  text: string;
}

export interface WhyJoinItem {
  icon: string;
  title: string;
  description: string;
}

export interface ProcessStep {
  title: string;
  description: string;
}

export interface LifeImage {
  src: string;
  alt: string;
  caption?: string;
}

/**
 * Career page content edited from /admin/careers/settings.
 */
export interface CareerSettings {
  hero: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    description: string;

    primaryCta: {
      text: string;
      href: string;
    };

    secondaryCta: {
      text: string;
      href: string;
    };

    image: string;
  };

  whyJoin: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    subtitle: string;
    items: WhyJoinItem[];
  };

  life: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    subtitle: string;
    images: LifeImage[];
  };

  process: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    subtitle: string;
    steps: ProcessStep[];
  };

  testimonials: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    subtitle: string;
    items: CareerTestimonial[];
  };

  benefits: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    subtitle: string;
    items: CareerBenefit[];
  };

  faqs: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    subtitle: string;
    items: CareerFaq[];
  };

  general: {
    eyebrow: string;
    title: string;
    titleHighlight?: string;
    subtitle: string;
    ctaTitle: string;
    ctaDescription: string;
  };
}
